<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Database\Factories\ProjectFactory;

class Project extends Model
{
    use HasFactory;

    protected $fillable =
    [
        'name',
        'description',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden =
    [
        'created_at',
        'updated_at',
        'pivot' // the pivot relationship property is generated by Laravel, but is unnecesary
    ];

    protected $with =
    [
        // 'meetingEvents' // $this->meetingEvents() method
    ];

    // relationship to MeetingEvent model ('meeting_events' table)
    public function meetingEvents()
    {
        /* Laravel uses naming conventions to figure out corresponding tables and columns names,
        but if the names of thables or key do not fit with Laravel conventions, the loading of nested
        resources won't work, so exact names are specified here */
        return $this->belongsToMany(MeetingEvent::class, // the model class coresponding to the related resource
                                    'meetings_projects_pivot', // name of pivot table that makes the connection
                                    'project_id_fk', // pivot table key pointing to this resource (Project)
                                    'meeting_id_fk' // pivot table key pointing to the other resource (MeetingEvent)
                                );
    }

    // explicitly specify what factory is associated with this model class
    // otherwise Laravel will try to use naming conventions to figure out
    // the corresponding factory
    protected static function newFactory(): Factory
    {
        return ProjectFactory::new();
    }
}
